### ISSUE TITLE
动画生成工具和$loading手动删除的疑问

### ISSUE THREAD

**Issue by yuantingjun** [lin-xin/vue-toast#17]
1. 请问下面的动画是用什么工具生成的吗？
```css
@keyframes opacity-11 {
    0% {
        opacity: 0.895958333333333;
    }
    91.6767% {
        opacity: 0.25;
    }
    91.6867% {
        opacity: 1;
    }
    51.6767% {
        opacity: 0.25;
    }
    100% {
        opacity: 0.895958333333333;
    }
}
```
2. $loading 关闭时为什么要删除DOM，而$toast 仅是控制DOM的显示隐藏，如果$loading也只是控制DOM的显示隐藏是不是更高效些？
